// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockMapSvelte.Infrastructure.Database;

#nullable disable

namespace StockMapSvelte.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "702f52fd-f23b-462d-b84b-0e1acc17785c",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "702f52fd-f23b-462d-b84b-0e1acc17785c",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "702f52fd-f23b-462d-b84b-0e1acc17785c",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "b3546cea-bc20-4f06-9341-15fb80768cf6",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "b3546cea-bc20-4f06-9341-15fb80768cf6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "505aedf9-29e3-4728-a8f0-d295040dbaef",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PortfolioStock", b =>
                {
                    b.Property<Guid>("PortfoliosId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StocksId")
                        .HasColumnType("uuid");

                    b.HasKey("PortfoliosId", "StocksId");

                    b.HasIndex("StocksId");

                    b.ToTable("PortfolioStock");
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Stock");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a480000-0389-c018-9dbd-08de40aae72b"),
                            TickerSymbol = "AAPL"
                        },
                        new
                        {
                            Id = new Guid("9a480000-0389-c018-a702-08de40aae72b"),
                            TickerSymbol = "MSFT"
                        },
                        new
                        {
                            Id = new Guid("9a480000-0389-c018-a70b-08de40aae72b"),
                            TickerSymbol = "GOOGL"
                        },
                        new
                        {
                            Id = new Guid("9a480000-0389-c018-a70e-08de40aae72b"),
                            TickerSymbol = "AVGO"
                        },
                        new
                        {
                            Id = new Guid("9a480000-0389-c018-a712-08de40aae72b"),
                            TickerSymbol = "RKLB"
                        },
                        new
                        {
                            Id = new Guid("9a480000-0389-c018-a7c2-08de40aae72b"),
                            TickerSymbol = "TSLA"
                        });
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.StockProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalystRecommendationKey")
                        .HasColumnType("text");

                    b.Property<double?>("AnalystRecommendationMean")
                        .HasColumnType("double precision");

                    b.Property<double?>("Beta")
                        .HasColumnType("double precision");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DividendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("DividendYield")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset?>("EarningsDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExDividendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("ForwardPe")
                        .HasColumnType("double precision");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<double?>("MarketCap")
                        .HasColumnType("double precision");

                    b.Property<string>("MarketState")
                        .HasColumnType("text");

                    b.Property<double?>("Pe")
                        .HasColumnType("double precision");

                    b.Property<double?>("PostMarketChangePercent")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PostMarketPrice")
                        .HasColumnType("numeric");

                    b.Property<double?>("PreMarketChangePercent")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("PreMarketPrice")
                        .HasColumnType("numeric");

                    b.Property<double?>("RegularMarketChangePercent")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("RegularMarketPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.Property<double?>("ShortRatio")
                        .HasColumnType("double precision");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StockId")
                        .IsUnique();

                    b.ToTable("StockProfile");
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.UserSetting", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid?>("DefaultPortfolioId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ToastAutoHide")
                        .HasColumnType("boolean");

                    b.Property<int>("ToastAutoHideDelayMs")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("UserSetting");
                });

            modelBuilder.Entity("StockMapSvelte.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "702f52fd-f23b-462d-b84b-0e1acc17785c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b09a83ae-cfd3-4ee7-97e6-fbcf0b0fe78c",
                            Email = "admin@rucen.me",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@RUCEN.ME",
                            NormalizedUserName = "ADMIN@RUCEN.ME",
                            PasswordHash = "AQAAAAEAACcQAAAAEAzK2mB/YP6hSw5/c3BRuPSGhRlPFTp3arEGy9CGpYWSZ8XJju1yweq/2+PFzGVm6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "SEJEPXC646ZBNCDYSM3H5FRK5RWP2TN6",
                            TwoFactorEnabled = false,
                            UserName = "admin@rucen.me"
                        },
                        new
                        {
                            Id = "b3546cea-bc20-4f06-9341-15fb80768cf6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a8d96fd-5918-441b-b800-cbafa99de97b",
                            Email = "manager@rucen.me",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "MANAGER@RUCEN.ME",
                            NormalizedUserName = "MANAGER@RUCEN.ME",
                            PasswordHash = "AQAAAAEAACcQAAAAEOZ07qoUUL9pwMR8+7xXWsldAicD2CFC6ufJsMWSYzFu9J8P3XCL9/tCxVMAKqyuaA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "MAJXOSATJKOEM4YFF32Y5G2XPR5OFEL6",
                            TwoFactorEnabled = false,
                            UserName = "manager@rucen.me"
                        },
                        new
                        {
                            Id = "505aedf9-29e3-4728-a8f0-d295040dbaef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acc87749-389b-4b5f-980c-0f3a49a37041",
                            Email = "demo@rucen.me",
                            EmailConfirmed = true,
                            LockoutEnabled = true,
                            NormalizedEmail = "DEMO@RUCEN.ME",
                            NormalizedUserName = "DEMO@RUCEN.ME",
                            PasswordHash = "AQAAAAEAACcQAAAAEF6Y+gXuBs8BQjWlNGbt586Sj20CDUvlsbLiWv+dP/+HawSCt4i+oXRH7g9DWHX+RA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "TEJXOSATJKOEB4YFF32Y5G2XPR5OFEL7",
                            TwoFactorEnabled = false,
                            UserName = "demo@rucen.me"
                        });
                });

            modelBuilder.Entity("StockMapSvelte.Infrastructure.Identity.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "9cf14c2c-19e7-40d6-b744-8917505c3106",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "be0efcde-9d0a-461d-8eb6-444b043d6660",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "29dafca7-cd20-4cd9-a3dd-4779d7bac3ee",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMapSvelte.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PortfolioStock", b =>
                {
                    b.HasOne("StockMapSvelte.Domain.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfoliosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockMapSvelte.Domain.Entities.Stock", null)
                        .WithMany()
                        .HasForeignKey("StocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.StockProfile", b =>
                {
                    b.HasOne("StockMapSvelte.Domain.Entities.Stock", "Stock")
                        .WithOne("StockProfile")
                        .HasForeignKey("StockMapSvelte.Domain.Entities.StockProfile", "StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.UserSetting", b =>
                {
                    b.HasOne("StockMapSvelte.Infrastructure.Identity.ApplicationUser", null)
                        .WithOne("UserSetting")
                        .HasForeignKey("StockMapSvelte.Domain.Entities.UserSetting", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockMapSvelte.Domain.Entities.Stock", b =>
                {
                    b.Navigation("StockProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("StockMapSvelte.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
